[package]
name = "rust-aws-devops"
version = "0.1.0"
authors = ["Mike McGirr <mike@fpcomplete.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusoto_core = "0.42.0"
rusoto_s3 = "0.42.0"
structopt = "0.3.9"
