[package]
name = "rust-aws-devops"
version = "0.1.0"
authors = ["Mike McGirr <mike@oatsmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
